export const orderTypes = {
  SAVE_ORDER_HISTORY: "SAVE_ORDER_HISTORY",
  GET_USER_HISTORY: "GET_USER_HISTORY",
  SET_USER_HISTORY: "SET_USER_HISTORY",
  GET_ORDER_DETAILS: "GET_ORDER_DETAILS",
  SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
};
